# coding: utf-8

"""
    GNBR Knowledge Beacon API

    This is the GNBR Knowledge Beacon web service application programming interface (API).   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: srensi@stanford.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.exact_match_response import ExactMatchResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestExactMatchResponse(unittest.TestCase):
    """ExactMatchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExactMatchResponse(self):
        """Test ExactMatchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.exact_match_response.ExactMatchResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
