# coding: utf-8

"""
    Translator Knowledge Beacon API

    This is the Translator Knowledge Beacon web service application programming interface (API).   # noqa: E501

    OpenAPI spec version: 1.0.16
    Contact: richard@starinformatics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.beacon_concept_type import BeaconConceptType  # noqa: E501
from swagger_client.rest import ApiException


class TestBeaconConceptType(unittest.TestCase):
    """BeaconConceptType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBeaconConceptType(self):
        """Test BeaconConceptType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.beacon_concept_type.BeaconConceptType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
