# coding: utf-8

"""
    GNBR Knowledge Beacon API

    This is the GNBR Knowledge Beacon web service application programming interface (API).   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: srensi@stanford.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import gnbr_beacon
from gnbr_beacon.api.concepts_api import ConceptsApi  # noqa: E501
from gnbr_beacon.rest import ApiException


class TestConceptsApi(unittest.TestCase):
    """ConceptsApi unit test stubs"""

    def setUp(self):
        self.api = gnbr_beacon.api.concepts_api.ConceptsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_concept_details(self):
        """Test case for get_concept_details

        """
        pass

    def test_get_concepts(self):
        """Test case for get_concepts

        """
        pass

    def test_get_exact_matches_to_concept_list(self):
        """Test case for get_exact_matches_to_concept_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
