# coding: utf-8

"""
    GNBR Knowledge Beacon API

    This is the GNBR Knowledge Beacon web service application programming interface (API).   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: srensi@stanford.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.beacon_knowledge_map_object import BeaconKnowledgeMapObject  # noqa: E501
from swagger_client.rest import ApiException


class TestBeaconKnowledgeMapObject(unittest.TestCase):
    """BeaconKnowledgeMapObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBeaconKnowledgeMapObject(self):
        """Test BeaconKnowledgeMapObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.beacon_knowledge_map_object.BeaconKnowledgeMapObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
