# coding: utf-8

"""
    GNBR Knowledge Beacon API

    This is the GNBR Knowledge Beacon web service application programming interface (API).   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: srensi@stanford.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import gnbr_beacon
from gnbr_beacon.models.beacon_statement_subject import BeaconStatementSubject  # noqa: E501
from gnbr_beacon.rest import ApiException


class TestBeaconStatementSubject(unittest.TestCase):
    """BeaconStatementSubject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBeaconStatementSubject(self):
        """Test BeaconStatementSubject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gnbr_beacon.models.beacon_statement_subject.BeaconStatementSubject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
