# coding: utf-8

"""
    Translator Knowledge Beacon API

    This is the Translator Knowledge Beacon web service application programming interface (API).   # noqa: E501

    OpenAPI spec version: 1.0.16
    Contact: richard@starinformatics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.statements_api import StatementsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStatementsApi(unittest.TestCase):
    """StatementsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.statements_api.StatementsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_evidence(self):
        """Test case for get_evidence

        """
        pass

    def test_get_statements(self):
        """Test case for get_statements

        """
        pass


if __name__ == '__main__':
    unittest.main()
