# coding: utf-8

"""
    GNBR Knowledge Beacon API

    This is the GNBR Knowledge Beacon web service application programming interface (API).   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: srensi@stanford.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BeaconConceptCategory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'category': 'str',
        'description': 'str',
        'frequency': 'int',
        'id': 'str',
        'local_category': 'str',
        'local_id': 'str',
        'local_uri': 'str',
        'uri': 'str'
    }

    attribute_map = {
        'category': 'category',
        'description': 'description',
        'frequency': 'frequency',
        'id': 'id',
        'local_category': 'local_category',
        'local_id': 'local_id',
        'local_uri': 'local_uri',
        'uri': 'uri'
    }

    def __init__(self, category=None, description=None, frequency=None, id=None, local_category=None, local_id=None, local_uri=None, uri=None):  # noqa: E501
        """BeaconConceptCategory - a model defined in Swagger"""  # noqa: E501

        self._category = None
        self._description = None
        self._frequency = None
        self._id = None
        self._local_category = None
        self._local_id = None
        self._local_uri = None
        self._uri = None
        self.discriminator = None

        if category is not None:
            self.category = category
        if description is not None:
            self.description = description
        if frequency is not None:
            self.frequency = frequency
        if id is not None:
            self.id = id
        if local_category is not None:
            self.local_category = local_category
        if local_id is not None:
            self.local_id = local_id
        if local_uri is not None:
            self.local_uri = local_uri
        if uri is not None:
            self.uri = uri

    @property
    def category(self):
        """Gets the category of this BeaconConceptCategory.  # noqa: E501

        human readable name (\"rdfs:label\")  # noqa: E501

        :return: The category of this BeaconConceptCategory.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this BeaconConceptCategory.

        human readable name (\"rdfs:label\")  # noqa: E501

        :param category: The category of this BeaconConceptCategory.  # noqa: E501
        :type: str
        """

        self._category = category

    @property
    def description(self):
        """Gets the description of this BeaconConceptCategory.  # noqa: E501

        human readable name definition of the category  # noqa: E501

        :return: The description of this BeaconConceptCategory.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this BeaconConceptCategory.

        human readable name definition of the category  # noqa: E501

        :param description: The description of this BeaconConceptCategory.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def frequency(self):
        """Gets the frequency of this BeaconConceptCategory.  # noqa: E501

        the number of concept entries of the specified type in the beacon knowledge base  # noqa: E501

        :return: The frequency of this BeaconConceptCategory.  # noqa: E501
        :rtype: int
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency):
        """Sets the frequency of this BeaconConceptCategory.

        the number of concept entries of the specified type in the beacon knowledge base  # noqa: E501

        :param frequency: The frequency of this BeaconConceptCategory.  # noqa: E501
        :type: int
        """

        self._frequency = frequency

    @property
    def id(self):
        """Gets the id of this BeaconConceptCategory.  # noqa: E501

        the CURIE of the concept category  # noqa: E501

        :return: The id of this BeaconConceptCategory.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BeaconConceptCategory.

        the CURIE of the concept category  # noqa: E501

        :param id: The id of this BeaconConceptCategory.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def local_category(self):
        """Gets the local_category of this BeaconConceptCategory.  # noqa: E501

        human readable local semantic type name (\"rdfs:label\")  # noqa: E501

        :return: The local_category of this BeaconConceptCategory.  # noqa: E501
        :rtype: str
        """
        return self._local_category

    @local_category.setter
    def local_category(self, local_category):
        """Sets the local_category of this BeaconConceptCategory.

        human readable local semantic type name (\"rdfs:label\")  # noqa: E501

        :param local_category: The local_category of this BeaconConceptCategory.  # noqa: E501
        :type: str
        """

        self._local_category = local_category

    @property
    def local_id(self):
        """Gets the local_id of this BeaconConceptCategory.  # noqa: E501

        the locally designated CURIE of the concept category  # noqa: E501

        :return: The local_id of this BeaconConceptCategory.  # noqa: E501
        :rtype: str
        """
        return self._local_id

    @local_id.setter
    def local_id(self, local_id):
        """Sets the local_id of this BeaconConceptCategory.

        the locally designated CURIE of the concept category  # noqa: E501

        :param local_id: The local_id of this BeaconConceptCategory.  # noqa: E501
        :type: str
        """

        self._local_id = local_id

    @property
    def local_uri(self):
        """Gets the local_uri of this BeaconConceptCategory.  # noqa: E501

        This locally designated category URI should generally  resolve to the full semantic description of the category  # noqa: E501

        :return: The local_uri of this BeaconConceptCategory.  # noqa: E501
        :rtype: str
        """
        return self._local_uri

    @local_uri.setter
    def local_uri(self, local_uri):
        """Sets the local_uri of this BeaconConceptCategory.

        This locally designated category URI should generally  resolve to the full semantic description of the category  # noqa: E501

        :param local_uri: The local_uri of this BeaconConceptCategory.  # noqa: E501
        :type: str
        """

        self._local_uri = local_uri

    @property
    def uri(self):
        """Gets the uri of this BeaconConceptCategory.  # noqa: E501

        The category URI which should generally resolves to  the full semantic description of the category  # noqa: E501

        :return: The uri of this BeaconConceptCategory.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this BeaconConceptCategory.

        The category URI which should generally resolves to  the full semantic description of the category  # noqa: E501

        :param uri: The uri of this BeaconConceptCategory.  # noqa: E501
        :type: str
        """

        self._uri = uri

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BeaconConceptCategory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
