# coding: utf-8

"""
    GNBR Knowledge Beacon API

    This is the GNBR Knowledge Beacon web service application programming interface (API).   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: srensi@stanford.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from gnbr_beacon.models.beacon_statement_object import BeaconStatementObject  # noqa: F401,E501
from gnbr_beacon.models.beacon_statement_predicate import BeaconStatementPredicate  # noqa: F401,E501
from gnbr_beacon.models.beacon_statement_subject import BeaconStatementSubject  # noqa: F401,E501


class BeaconStatement(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'object': 'BeaconStatementObject',
        'predicate': 'BeaconStatementPredicate',
        'subject': 'BeaconStatementSubject'
    }

    attribute_map = {
        'id': 'id',
        'object': 'object',
        'predicate': 'predicate',
        'subject': 'subject'
    }

    def __init__(self, id=None, object=None, predicate=None, subject=None):  # noqa: E501
        """BeaconStatement - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._object = None
        self._predicate = None
        self._subject = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if object is not None:
            self.object = object
        if predicate is not None:
            self.predicate = predicate
        if subject is not None:
            self.subject = subject

    @property
    def id(self):
        """Gets the id of this BeaconStatement.  # noqa: E501

        CURIE-encoded identifier for statement (can be used to retrieve associated evidence)  # noqa: E501

        :return: The id of this BeaconStatement.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BeaconStatement.

        CURIE-encoded identifier for statement (can be used to retrieve associated evidence)  # noqa: E501

        :param id: The id of this BeaconStatement.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def object(self):
        """Gets the object of this BeaconStatement.  # noqa: E501


        :return: The object of this BeaconStatement.  # noqa: E501
        :rtype: BeaconStatementObject
        """
        return self._object

    @object.setter
    def object(self, object):
        """Sets the object of this BeaconStatement.


        :param object: The object of this BeaconStatement.  # noqa: E501
        :type: BeaconStatementObject
        """

        self._object = object

    @property
    def predicate(self):
        """Gets the predicate of this BeaconStatement.  # noqa: E501


        :return: The predicate of this BeaconStatement.  # noqa: E501
        :rtype: BeaconStatementPredicate
        """
        return self._predicate

    @predicate.setter
    def predicate(self, predicate):
        """Sets the predicate of this BeaconStatement.


        :param predicate: The predicate of this BeaconStatement.  # noqa: E501
        :type: BeaconStatementPredicate
        """

        self._predicate = predicate

    @property
    def subject(self):
        """Gets the subject of this BeaconStatement.  # noqa: E501


        :return: The subject of this BeaconStatement.  # noqa: E501
        :rtype: BeaconStatementSubject
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this BeaconStatement.


        :param subject: The subject of this BeaconStatement.  # noqa: E501
        :type: BeaconStatementSubject
        """

        self._subject = subject

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BeaconStatement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
