# coding: utf-8

# flake8: noqa
"""
    Translator Knowledge Beacon API

    This is the Translator Knowledge Beacon web service application programming interface (API).   # noqa: E501

    OpenAPI spec version: 1.0.16
    Contact: richard@starinformatics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.beacon_annotation import BeaconAnnotation
from swagger_client.models.beacon_concept import BeaconConcept
from swagger_client.models.beacon_concept_detail import BeaconConceptDetail
from swagger_client.models.beacon_concept_type import BeaconConceptType
from swagger_client.models.beacon_concept_with_details import BeaconConceptWithDetails
from swagger_client.models.beacon_predicate import BeaconPredicate
from swagger_client.models.beacon_statement import BeaconStatement
from swagger_client.models.beacon_statement_object import BeaconStatementObject
from swagger_client.models.beacon_statement_predicate import BeaconStatementPredicate
from swagger_client.models.beacon_statement_subject import BeaconStatementSubject
