# coding: utf-8

"""
    Translator Knowledge Beacon API

    This is the Translator Knowledge Beacon web service application programming interface (API).   # noqa: E501

    OpenAPI spec version: 1.0.16
    Contact: richard@starinformatics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BeaconPredicate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'definition': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'definition': 'definition'
    }

    def __init__(self, id=None, name=None, definition=None):  # noqa: E501
        """BeaconPredicate - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._definition = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if definition is not None:
            self.definition = definition

    @property
    def id(self):
        """Gets the id of this BeaconPredicate.  # noqa: E501

        CURIE-encoded identifier of predicate resource   # noqa: E501

        :return: The id of this BeaconPredicate.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BeaconPredicate.

        CURIE-encoded identifier of predicate resource   # noqa: E501

        :param id: The id of this BeaconPredicate.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this BeaconPredicate.  # noqa: E501

        human readable name of predicate relation   # noqa: E501

        :return: The name of this BeaconPredicate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BeaconPredicate.

        human readable name of predicate relation   # noqa: E501

        :param name: The name of this BeaconPredicate.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def definition(self):
        """Gets the definition of this BeaconPredicate.  # noqa: E501

        human readable definition of predicate relation provided by this beacon   # noqa: E501

        :return: The definition of this BeaconPredicate.  # noqa: E501
        :rtype: str
        """
        return self._definition

    @definition.setter
    def definition(self, definition):
        """Sets the definition of this BeaconPredicate.

        human readable definition of predicate relation provided by this beacon   # noqa: E501

        :param definition: The definition of this BeaconPredicate.  # noqa: E501
        :type: str
        """

        self._definition = definition

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BeaconPredicate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
