# coding: utf-8

"""
    Translator Knowledge Beacon API

    This is the Translator Knowledge Beacon web service application programming interface (API).   # noqa: E501

    OpenAPI spec version: 1.0.16
    Contact: richard@starinformatics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BeaconAnnotation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'label': 'str',
        'type': 'str',
        'date': 'str'
    }

    attribute_map = {
        'id': 'id',
        'label': 'label',
        'type': 'type',
        'date': 'date'
    }

    def __init__(self, id=None, label=None, type=None, date=None):  # noqa: E501
        """BeaconAnnotation - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._label = None
        self._type = None
        self._date = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if label is not None:
            self.label = label
        if type is not None:
            self.type = type
        if date is not None:
            self.date = date

    @property
    def id(self):
        """Gets the id of this BeaconAnnotation.  # noqa: E501

        CURIE-encoded identifier to an associated external resources (e.g. PMID of a pubmed citation)   # noqa: E501

        :return: The id of this BeaconAnnotation.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BeaconAnnotation.

        CURIE-encoded identifier to an associated external resources (e.g. PMID of a pubmed citation)   # noqa: E501

        :param id: The id of this BeaconAnnotation.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this BeaconAnnotation.  # noqa: E501

        canonical human readable and searchable label of the annotation (i.e. comment, matched sentence, etc.)   # noqa: E501

        :return: The label of this BeaconAnnotation.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this BeaconAnnotation.

        canonical human readable and searchable label of the annotation (i.e. comment, matched sentence, etc.)   # noqa: E501

        :param label: The label of this BeaconAnnotation.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def type(self):
        """Gets the type of this BeaconAnnotation.  # noqa: E501

        Gene Ontology Evidence Code (http://www.geneontology.org/page/guide-go-evidence-codes)   # noqa: E501

        :return: The type of this BeaconAnnotation.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this BeaconAnnotation.

        Gene Ontology Evidence Code (http://www.geneontology.org/page/guide-go-evidence-codes)   # noqa: E501

        :param type: The type of this BeaconAnnotation.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def date(self):
        """Gets the date of this BeaconAnnotation.  # noqa: E501

        publication date of annotation (generally of format 'yyyy-mm-dd')   # noqa: E501

        :return: The date of this BeaconAnnotation.  # noqa: E501
        :rtype: str
        """
        return self._date

    @date.setter
    def date(self, date):
        """Sets the date of this BeaconAnnotation.

        publication date of annotation (generally of format 'yyyy-mm-dd')   # noqa: E501

        :param date: The date of this BeaconAnnotation.  # noqa: E501
        :type: str
        """

        self._date = date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BeaconAnnotation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
